facebook_clone/config/routes.rb
Rails.application.routes.draw do
  resources :posts
  get 'users/index'

  get 'users/show'

  devise_for :users
  root to: 'home#index'

  resources :users, only: [:index, :show] do 
    resources :messages

  end

end

facebook_clone/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

facebook_clone/app/models/follow.rb
class Follow < Socialization::ActiveRecordStores::Follow
end

facebook_clone/app/models/like.rb
class Like < Socialization::ActiveRecordStores::Like
end

facebook_clone/app/models/mention.rb
class Mention < Socialization::ActiveRecordStores::Mention
end

facebook_clone/app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user, class_name: "User"
end

facebook_clone/app/models/public_activity.rb
class Article < ActiveRecord::Base
	include PublicActivity::Model
	tracked
end

facebook_clone/app/models/user.rb
class User < ActiveRecord::Base
	# has_attached_file :avatar, styles: {medium: "300x300", thumb: "100x100">}, default_url: "/images/:style/missing.png"
	# validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
	 

	has_many :posts

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :email, presence: true
end

facebook_clone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :find_users
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) { |u| u.permit({ roles: [] }, :email, :password, :password_confirmation)}
  end

  private

  def not_authenticated
  	redirect_to login_path
  end

  def find_users
  	@users = User.all
  end

end

facebook_clone/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

facebook_clone/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

facebook_clone/app/controllers/notifications_controller.rb
# notifications_controller.rb

def index
	@activities = PublicActivity::Activity.all
end

facebook_clone/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @post = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find params[:id]
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post].permit(:title, :text))
    @post.save
    redirect_to @post 

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:user_id, :content)
    end
end

facebook_clone/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to(@user)
    else
      render 'edit'
    end
  end

  def new
    @user = User.new
  end

  def index
  end

  def show
  end

  def create
  	@user = User.create(user_params)
  end

  private

  def user_params
  	params.require(:user).permit(:avatar)
  end

end

facebook_clone/app/helpers/application_helper.rb
module ApplicationHelper
end

facebook_clone/app/helpers/comments_helper.rb
module CommentsHelper
end

facebook_clone/app/helpers/home_helper.rb
module HomeHelper
end

facebook_clone/app/helpers/posts_helper.rb
module PostsHelper
end

facebook_clone/app/helpers/users_helper.rb
module UsersHelper
end

facebook_clone/app/views/home/index.html.erb
<%= render 'posts/form' %>
<% @activities.each do |activity| %>
<%= render_activity(activity) %>
<% end %>

facebook_clone/app/views/layouts/Page_Layout.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "FacebookClone" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">FacebookClone</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2015</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

facebook_clone/app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :class => "flash_#{name}" %>
  <% end %>
<% end %>

facebook_clone/app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li><%= link_to 'Home', root_path %></li>
  <%= render 'layouts/navigation_links' %>
  <%# add navigation links to this file %>
</ul>

facebook_clone/app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

facebook_clone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title>Facebook Clone</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Facebook Clone" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Facebook Clone" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </main>
  </body>
</html>

facebook_clone/app/views/posts/_form.html.erb
<%= form_for :post, url: post_path do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
    </div>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

facebook_clone/app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= form_for @post do |f| %>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

<% end %>

facebook_clone/app/views/posts/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<h1>Listing Posts</h1>
  <% @posts.each do |post| %>
    <h2><%= link_to post.title, post_path(post) %></h2>
    <p><%= post.content %></p>
    <hr/>
  <% end %>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.user_id %></td>
        <td><%= post.content %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

facebook_clone/app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

facebook_clone/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @post.user_id %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

facebook_clone/app/views/public_activity/index.html.erb
<%= render_activities(@activities) %>

facebook_clone/app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => "form-horizontal user" } do |f| %>

<%= render 'posts/form' %>


    <% if @user.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'form-control' %>
    </div>
    <%= error_span(@user[:email]) %>
  </div>
  <div class="control-group">
    <%= f.label :encrypted_password, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :encrypted_password, :class => 'form-control' %>
    </div>
    <%= error_span(@user[:encrypted_password]) %>
  </div>
  <div class="control-group">
    <%= f.label :reset_password_token, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :reset_password_token, :class => 'form-control' %>
    </div>
    <%= error_span(@user[:reset_password_token]) %>
  </div>
  <div class="control-group">
    <%= f.label :reset_password_sent_at, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :reset_password_sent_at, :class => 'form-control' %>
    </div>
    <%= error_span(@user[:reset_password_sent_at]) %>
  </div>
  <div class="control-group">
    <%= f.label :remember_created_at, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :remember_created_at, :class => 'form-control' %>
    </div>
    <%= error_span(@user[:remember_created_at]) %>
  </div>
  <div class="control-group">
    <%= f.label :current_sign_in_at, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :current_sign_in_at, :class => 'form-control' %>
    </div>
    <%= error_span(@user[:current_sign_in_at]) %>
  </div>
  <div class="control-group">
    <%= f.label :last_sign_in_at, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :last_sign_in_at, :class => 'form-control' %>
    </div>
    <%= error_span(@user[:last_sign_in_at]) %>
  </div>
  <div class="control-group">
    <%= f.label :current_sign_in_ip, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :current_sign_in_ip, :class => 'form-control' %>
    </div>
    <%= error_span(@user[:current_sign_in_ip]) %>
  </div>
  <div class="control-group">
    <%= f.label :last_sign_in_ip, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :last_sign_in_ip, :class => 'form-control' %>
    </div>
    <%= error_span(@user[:last_sign_in_ip]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            users_path, :class => 'btn btn-default' %>

<% end %>

facebook_clone/app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

<%= form_for @user, url: users_path, html: { multipart: true } do |form| %>
	<%= form.file_field :avatar %>
<% end %>

facebook_clone/app/views/users/follow.js.erb
$('.user-<%= @user.id %> > #follow_form').html("<%= escape_javascript(render 'shared/unfollow', user: @user) %>")

facebook_clone/app/views/users/index.html.erb
<%= render @users %>

facebook_clone/app/views/users/new.html.erb
<h1>New User</h1>
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

<%= link_to 'Back', users_path %>

facebook_clone/app/views/users/show.html.erb
<div class="right">
	<% if user_signed_in? %>
	<%= render 'shared/follow_form', user: @user %>
	<% end %>
</div>

<%= image_tag @user.avatar.url(:thumb), class: 'profile' %>
<span class="left">
	<h4><%= @user.name %></h4>
</span>

<div class="row feed">
	<% @activities.each do |activity| %>
	<%= render_activity(activity) %>
	<% end %>
</div>

<%= image_tag @user.avatar.url %>
<%= image_tag @user.avatar.url(:medium) %>
<%= image_tag @user.avatar.url(:thumb) %>